kill_chain_phase = ['Recon','Weaponize','Deliver','Exploit','Control','Execute','Maintain']
enforcement_level = ['Network','Device','Application','Data','People']
security_function = ['Identify','Protect','Detect','Respond','Recover']
business_domain = ['Finance','Education','Accomodation','Entertainment','Finacne','Healthcare','Information','Management']
asset_type = ['Web Application','Laptop','Documents']